import { Route } from "react-router-dom";
import { Routes } from "react-router-dom";

import Layout from "./layout/layout";
import Cart from "./pages/shopCart";
import Main from "./pages/main";
import List from "./pages/itemsList";
import Checkout from "./pages/checkout";

function App() {
  let data = {
    0: {
      picture:
        "https://images.unsplash.com/photo-1629956044156-27896de7efa1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8b25lfGVufDB8fDB8fHww&w=1000&q=80",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    1: {
      picture:
        "https://cdn.pixabay.com/photo/2012/05/04/10/18/two-47085_1280.png",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    2: {
      picture:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRagIPixpfhdLWExhOBEL50IBKR31TS0zZiCne4Iw1C1g&s",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    3: {
      picture:
        "https://t4.ftcdn.net/jpg/00/99/53/31/360_F_99533104_L1KKBU8pLtGjUSckCncSaSOHMrj14bAG.jpg",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    4: {
      picture:
        "https://www.shutterstock.com/image-illustration/3d-shiny-red-number-collection-260nw-120044455.jpg",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    5: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    6: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    7: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    8: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    9: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    10: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    11: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    12: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    13: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    14: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    15: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    16: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    17: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    18: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    19: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    20: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    21: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    22: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    23: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    24: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    25: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    26: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    27: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    28: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    29: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    30: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    31: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    32: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    33: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    34: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    35: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    36: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    37: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    38: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    39: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    40: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    41: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    42: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    43: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    44: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    45: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    46: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    47: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    48: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    49: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    50: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    51: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    52: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    53: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    54: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    55: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    56: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    57: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    58: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    59: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    60: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    61: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    62: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    63: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    64: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
    65: {
      picture: "firstPic",
      name: "firstName",
      description: "descOfFirstItem",
      price: 1,
      page: "linkToFirstPage",
      type: "jeans",
    },
    66: {
      picture: "secondPic",
      name: "secondName",
      description: "descOfSecondItem",
      price: 2,
      page: "linkToSecondPage",
      type: "shoes",
    },
    67: {
      picture: "thirdPic",
      name: "thirdName",
      description: "descOfThirdItem",
      price: 3,
      page: "linkToThirdPage",
      type: "jeans",
    },
    68: {
      picture: "fourthPic",
      name: "fourthName",
      description: "descOfFourthItem",
      price: 4,
      page: "linkToFourthPage",
      type: "shoes",
    },
    69: {
      picture: "fifthPic",
      name: "fifthName",
      description: "descOfFifthItem",
      price: 5,
      page: "linkToFifthPage",
      type: "tshirt",
    },
  };

  return (
    <div>
      <Layout>
        <Routes>
          <Route path="/" element={<Main data={data} />} />
          <Route path="/list" element={<List data={data} />} />
          <Route
            path="/list-shoes"
            element={<List data={data} type="shoes" />}
          />
          <Route
            path="/list-jeans"
            element={<List data={data} type="jeans" />}
          />
          <Route
            path="/list-tshirt"
            element={<List data={data} type="tshirt" />}
          />
          <Route path="/cart" element={<Cart data={data} />} />
          <Route path="/checkout" element={<Checkout />} />
        </Routes>
      </Layout>
    </div>
  );
}

export default App;
